### ISSUE TITLE
Lineage 16

### ISSUE THREAD

**Issue by kiam001** [Sohamlad7/android_vendor_motorola_cedric#6]
[ 99% 809/810] glob frameworks/base/core/res/res/**/*
ninja: error: 'vendor/motorola/cedric/proprietary/app/TimeService/TimeService.apk', needed by '/home/maik/build/out/target/product/cedric/obj/APPS/TimeService_intermediates/package.apk', missing and no known rule to make it
17:55:31 ninja failed with: exit status 1

**Comment by vahbuna** [comment]
hi @kiam001 

were you able resolve this issue? how?

thx
